seed: 42
save_steps: 1000

window_size: 10
train_ratio: 0.7
logging_steps: 1000

learning_rate: 3e-5
num_train_epochs: 200
train_batch_size: 16
eval_batch_size: 16

save_predictions: true
save_model: true

data_dir: ./data
model_dir: ./output
prediction_dir: ./prediction
